name: C/C++ CI

on:
  push:
    branches: [ "main", "extra" ]
  pull_request:
    branches: [ "main", "extra" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
